export const countryCodes = [
    { "code": "+1", "label": "United States/Canada" },
    { "code": "+44", "label": "United Kingdom" },
    { "code": "+358", "label": "Finland" },
    { "code": "+91", "label": "India" },
    { "code": "+61", "label": "Australia" },
    { "code": "+81", "label": "Japan" },
    { "code": "+49", "label": "Germany" },
    { "code": "+33", "label": "France" },
    { "code": "+39", "label": "Italy" },
    { "code": "+34", "label": "Spain" },
    { "code": "+86", "label": "China" },
    { "code": "+7", "label": "Russia" },
    { "code": "+55", "label": "Brazil" },
    { "code": "+27", "label": "South Africa" },
    { "code": "+82", "label": "South Korea" },
    { "code": "+972", "label": "Israel" },
    { "code": "+964", "label": "Iraq" },
    { "code": "+966", "label": "Saudi Arabia" },
    { "code": "+90", "label": "Turkey" },
    { "code": "+48", "label": "Poland" },
    { "code": "+213", "label": "Algeria" },
    { "code": "+244", "label": "Angola" },
    { "code": "+229", "label": "Benin" },
    { "code": "+267", "label": "Botswana" },
    { "code": "+226", "label": "Burkina Faso" },
    { "code": "+257", "label": "Burundi" },
    { "code": "+237", "label": "Cameroon" },
    { "code": "+238", "label": "Cape Verde" },
    { "code": "+236", "label": "Central African Republic" },
    { "code": "+235", "label": "Chad" },
    { "code": "+269", "label": "Comoros" },
    { "code": "+242", "label": "Congo" },
    { "code": "+243", "label": "Democratic Republic of the Congo" },
    { "code": "+225", "label": "Ivory Coast" },
    { "code": "+253", "label": "Djibouti" },
    { "code": "+20", "label": "Egypt" },
    { "code": "+240", "label": "Equatorial Guinea" },
    { "code": "+291", "label": "Eritrea" },
    { "code": "+251", "label": "Ethiopia" },
    { "code": "+241", "label": "Gabon" },
    { "code": "+220", "label": "Gambia" },
    { "code": "+233", "label": "Ghana" },
    { "code": "+224", "label": "Guinea" },
    { "code": "+245", "label": "Guinea-Bissau" },
    { "code": "+254", "label": "Kenya" },
    { "code": "+266", "label": "Lesotho" },
    { "code": "+231", "label": "Liberia" },
    { "code": "+218", "label": "Libya" },
    { "code": "+261", "label": "Madagascar" },
    { "code": "+265", "label": "Malawi" },
    { "code": "+223", "label": "Mali" },
    { "code": "+222", "label": "Mauritania" },
    { "code": "+230", "label": "Mauritius" },
    { "code": "+212", "label": "Morocco" },
    { "code": "+258", "label": "Mozambique" },
    { "code": "+264", "label": "Namibia" },
    { "code": "+227", "label": "Niger" },
    { "code": "+234", "label": "Nigeria" },
    { "code": "+250", "label": "Rwanda" },
    { "code": "+239", "label": "Sao Tome and Principe" },
    { "code": "+221", "label": "Senegal" },
    { "code": "+248", "label": "Seychelles" },
    { "code": "+232", "label": "Sierra Leone" },
    { "code": "+252", "label": "Somalia" },
    { "code": "+27", "label": "South Africa" },
    { "code": "+211", "label": "South Sudan" },
    { "code": "+249", "label": "Sudan" },
    { "code": "+268", "label": "Swaziland" },
    { "code": "+255", "label": "Tanzania" },
    { "code": "+228", "label": "Togo" },
    { "code": "+216", "label": "Tunisia" },
    { "code": "+256", "label": "Uganda" },
    { "code": "+260", "label": "Zambia" },
    { "code": "+263", "label": "Zimbabwe" },
    { "code": "+354", "label": "Iceland" },
    { "code": "+353", "label": "Ireland" },
    { "code": "+972", "label": "Israel" },
    { "code": "+962", "label": "Jordan" },
    { "code": "+7", "label": "Kazakhstan" },
    { "code": "+254", "label": "Kenya" },
    { "code": "+996", "label": "Kyrgyzstan" },
    { "code": "+856", "label": "Laos" },
    { "code": "+371", "label": "Latvia" },
    { "code": "+961", "label": "Lebanon" },
    { "code": "+423", "label": "Liechtenstein" },
    { "code": "+370", "label": "Lithuania" },
    { "code": "+352", "label": "Luxembourg" },
    { "code": "+853", "label": "Macau" },
    { "code": "+389", "label": "North Macedonia" },
    { "code": "+60", "label": "Malaysia" },
    { "code": "+960", "label": "Maldives" },
    { "code": "+356", "label": "Malta" },
    { "code": "+692", "label": "Marshall Islands" },
    { "code": "+222", "label": "Mauritania" },
    { "code": "+52", "label": "Mexico" },
    { "code": "+691", "label": "Micronesia" },
    { "code": "+373", "label": "Moldova" },
    { "code": "+377", "label": "Monaco" },
    { "code": "+976", "label": "Mongolia" },
    { "code": "+382", "label": "Montenegro" },
    { "code": "+212", "label": "Morocco" },
    { "code": "+258", "label": "Mozambique" },
    { "code": "+95", "label": "Myanmar" },
    { "code": "+264", "label": "Namibia" },
    { "code": "+674", "label": "Nauru" },
    { "code": "+977", "label": "Nepal" },
    { "code": "+31", "label": "Netherlands" },
    { "code": "+687", "label": "New Caledonia" },
    { "code": "+64", "label": "New Zealand" },
    { "code": "+505", "label": "Nicaragua" },
    { "code": "+227", "label": "Niger" },
    { "code": "+234", "label": "Nigeria" },
    { "code": "+683", "label": "Niue" },
    { "code": "+850", "label": "North Korea" },
    { "code": "+47", "label": "Norway" },
    { "code": "+968", "label": "Oman" },
    { "code": "+92", "label": "Pakistan" },
    { "code": "+680", "label": "Palau" },
    { "code": "+970", "label": "Palestine" },
    { "code": "+507", "label": "Panama" },
    { "code": "+675", "label": "Papua New Guinea" },
    { "code": "+595", "label": "Paraguay" },
    { "code": "+51", "label": "Peru" },
    { "code": "+63", "label": "Philippines" },
    { "code": "+48", "label": "Poland" },
    { "code": "+351", "label": "Portugal" },
    { "code": "+974", "label": "Qatar" },
    { "code": "+40", "label": "Romania" },
    { "code": "+7", "label": "Russia" },
    { "code": "+250", "label": "Rwanda" },
    { "code": "+590", "label": "Saint Barthelemy" },
    { "code": "+290", "label": "Saint Helena" },
    { "code": "+1869", "label": "Saint Kitts and Nevis" },
    { "code": "+1758", "label": "Saint Lucia" },
    { "code": "+508", "label": "Saint Pierre and Miquelon" },
    { "code": "+1784", "label": "Saint Vincent and the Grenadines" },
    { "code": "+685", "label": "Samoa" },
    { "code": "+378", "label": "San Marino" },
    { "code": "+239", "label": "Sao Tome and Principe" },
    { "code": "+966", "label": "Saudi Arabia" },
    { "code": "+221", "label": "Senegal" },
    { "code": "+381", "label": "Serbia" },
    { "code": "+248", "label": "Seychelles" },
    { "code": "+232", "label": "Sierra Leone" },
    { "code": "+65", "label": "Singapore" },
    { "code": "+421", "label": "Slovakia" },
    { "code": "+386", "label": "Slovenia" },
    { "code": "+677", "label": "Solomon Islands" },
    { "code": "+252", "label": "Somalia" },
    { "code": "+27", "label": "South Africa" },
    { "code": "+211", "label": "South Sudan" },
    { "code": "+82", "label": "South Korea" },
    { "code": "+34", "label": "Spain" },
    { "code": "+94", "label": "Sri Lanka" },
    { "code": "+249", "label": "Sudan" },
    { "code": "+597", "label": "Suriname" },
    { "code": "+268", "label": "Swaziland" },
    { "code": "+46", "label": "Sweden" },
    { "code": "+41", "label": "Switzerland" },
    { "code": "+963", "label": "Syria" },
    { "code": "+886", "label": "Taiwan" },
    { "code": "+992", "label": "Tajikistan" },
    { "code": "+255", "label": "Tanzania" },
    { "code": "+66", "label": "Thailand" },
    { "code": "+228", "label": "Togo" },
    { "code": "+690", "label": "Tokelau" },
    { "code": "+676", "label": "Tonga" },
    { "code": "+1868", "label": "Trinidad and Tobago" },
    { "code": "+216", "label": "Tunisia" },
    { "code": "+90", "label": "Turkey" },
    { "code": "+993", "label": "Turkmenistan" },
    { "code": "+688", "label": "Tuvalu" },
    { "code": "+256", "label": "Uganda" },
    { "code": "+380", "label": "Ukraine" },
    { "code": "+971", "label": "United Arab Emirates" },
    { "code": "+44", "label": "United Kingdom" },
    { "code": "+1", "label": "United States/Canada" },
    { "code": "+598", "label": "Uruguay" },
    { "code": "+998", "label": "Uzbekistan" },
    { "code": "+678", "label": "Vanuatu" },
    { "code": "+58", "label": "Venezuela" },
    { "code": "+84", "label": "Vietnam" },
    { "code": "+681", "label": "Wallis and Futuna" },
    { "code": "+967", "label": "Yemen" },
    { "code": "+260", "label": "Zambia" },
    { "code": "+263", "label": "Zimbabwe" }
];